### ISSUE TITLE
incompatible with redmine 5.0.2 

### ISSUE THREAD

**Issue by damien-sorin** [masamitsu-murase/redmine_add_subversion_links#15]
Trying to run redmine with this plugin leads to _LoadError()_ with _redmine_add_subversion_links_application_helper_patch_.

Host:
- Ubuntu 22.04.1 LTS
- Apache2  (2.4.52 (Ubuntu))
- Passenger (6.0.10)
- ruby (3.0.2p107)
- Rails 6.1.6

Client:
- Chrome (104.0.5112.102)

Log-Output:
```
App 4981 output: Error: The application encountered the following error: cannot load such file -- redmine_add_subversion_links_application_helper_patch (LoadError)
App 4981 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
App 4981 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/plugins/redmine_add_subversion_links/init.rb:2:in `<top (required)>'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/lib/redmine/plugin_loader.rb:31:in `load'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/lib/redmine/plugin_loader.rb:31:in `run_initializer'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/lib/redmine/plugin_loader.rb:108:in `each'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/lib/redmine/plugin_loader.rb:108:in `block in load'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
App 4981 output:     /var/lib/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 4981 output:     /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
App 4981 output:     /var/lib/gems/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
App 4981 output:     /var/ankhmorpork/redmine/checkouts/redmine-5.0.2/config/environment.rb:16:in `<top (required)>'
App 4981 output:     config.ru:3:in `require'
App 4981 output:     config.ru:3:in `block in <main>'
App 4981 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `instance_eval'
App 4981 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `initialize'
App 4981 output:     config.ru:1:in `new'
App 4981 output:     config.ru:1:in `<main>'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 4981 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 4981 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```

**Comment by tmaidment** [comment]
I have the same issue, were you able to get it resolved?

**Comment by damien-sorin** [comment]
unfortunately not - I think its an incompatibility and someone has to modify the plugin to work with current versions of redmine.

**Comment by damien-sorin** [comment]
closed the issue, because it seems to be never fixed.
